"""Add generate_histories_id field to table generate_ouputs

Revision ID: c7ce088c2665
Revises: cd168edebb44
Create Date: 2024-08-28 16:45:00.806443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7ce088c2665'
down_revision: Union[str, None] = 'cd168edebb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generate_outputs', sa.Column('generate_histories_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generate_outputs', 'generate_histories_id')
    # ### end Alembic commands ###
