ssh:
  host: 3.93.68.57
  port: 22
  user: ec2-user
  private_key: src/config/gem-x-prod-system-admin.pem
  
db:
  host: image2layout-detection.chm9jqqz3liy.us-east-1.rds.amazonaws.com
  port: 5432
  name: postgres
  user: postgres
  password: Uxc6AyhAWe6nHsmv

db_issue:
  host: localhost
  port: 5432
  username: postgres
  password: 1
  db: generate_output_issues

save_path: result_test